### PR TITLE
Only partially wake the device for scans. Keeps the screen off.

### PR DESCRIPTION
**Pull request by dermotduffy**
See #5 for more details. Built & tested. Credit for the fix goes to the @MarcusNi96 . 

Details of different wake levels: https://developer.android.com/reference/android/os/PowerManager.html#summary

### CODE REVIEW

**Comment by dermotduffy** [comment]
[There may be network connectivity issues with this approach that are coming to light ... recommend not integrating until I can confirm this is good, or come up with a network keepalive]

**Comment by dermotduffy** [comment]
The issue here is that with only a partial wake lock, Android may doze the process, which kills the network connection. The trick is to disable battery optimization for the app, and then the connection is maintained. A better fix would maintain or re-establish the network connection in a different way, or at worst offer the user the intent to disable battery optimization.

As such, this PR may or may not be useful (personally, I think it's still better than waking up the screen, but perhaps needs some doc updates to warn people to disable battery optimization).

**Comment by daniele-athome** [comment]
Any news on this? I can program on Android and I'd like to help.

> The issue here is that with only a partial wake lock, Android may doze the process, which kills the network connection. The trick is to disable battery optimization for the app, and then the connection is maintained. 

That or a foreground notification.

Are there other issues preventing this from being merged?

Thanks!

EDIT: #24 is an issue.

**Comment by esatapedico** [comment]
Maybe keeping with the current wakelock but not using ACQUIRE_CAUSES_WAKEUP would be an option?

I'm no Android Developer (though I've messed quite a bit with customizing some phones), but the description of this constant seems like it's about the screen turning on.

Sure the minimum wake level the better, but if this would really prevent the screen from turning on while keeping the current behavior, it would already be a nice step forward.


See: https://developer.android.com/reference/android/os/PowerManager#ACQUIRE_CAUSES_WAKEUP

**Comment by daniele-athome** [comment]
@esatapedico starting Android 9 that could be a problem. See #24.

**Comment by dermotduffy** [comment]
I'm not using find3 anymore so cannot attest to the continued validity of this PR ... closing as a spring clean.

**Pull request closed without merging**
